[project]
name = "QuestHive"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.honey-token]
path = "contracts/honey-token.clar"
depends_on = []

[contracts.quests]
path = "contracts/quests.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
